### ISSUE TITLE
Recently Played includes songs with play counts of 0

### ISSUE THREAD

**Issue by stigsell** [Mpmart08/MusicPlayer#25]
I think it makes sense for the Recently Played playlist to exclude songs that have never been played.  Would you agree?

<img width="1438" alt="screenshot 2016-07-19 22 13 12" src="https://cloud.githubusercontent.com/assets/5466018/16974035/3e1447dc-4dfe-11e6-8cdd-700840835e67.png">

**Comment by Mpmart08** [comment]
Take a look at the latest commit, and let me know what you think
